services:
#    agile_Story_print_jira.example:
#        class: AgileStoryPrint\JiraBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


services:
    asp.mailer:
        class:        AgileStoryPrint\JiraBundle\Mailer\Mailer
        arguments:    [@mailer, @twig, '%mailer_admin_address%', '%mailer_noreply_address%', '%mailer_noreply_name%']
